var projectsData = {
  cencosud: {
    img:'cencosud/preview.jpg',
    title: 'Delivery flexibility Easy',
    client: 'Cencosud Easy',
    workplace: 'Midas',
    type: 'Web Application Dashboard',
    tools: ['ReactJS','ReduxJS','Html5','CSS3','AdobeXD','Material Design'],
    cat:'all reactjs',
    gallery:[1,2,3,4],
    description: 'Backoffice dashboard for the administration of delivery status in Argentina.'
  },
  ypfrequest: {
    img:'ypfrequest/preview.jpg',
    title: 'YPF request administration',
    client: 'YPF',
    workplace: 'Midas',
    type: 'Web Application Dashboard',
    tools: ['ReactJS','Html5','CSS3','AdobeXD'],
    cat:'all reactjs',
    gallery:[1],
    description: 'Backoffice dashboard for request administration.'
  },
  crowdi: {
    img:'crowdi/preview.jpg',
    title: 'Crowdi',
    client: 'Crowdi',
    workplace: 'Midas',
    type: 'React Web Application',
    tools: ['ReactJS','ReduxJS','Html5','CSS3','AdobeXD','Photoshop','Illustrator','Maling','Analytics'],
    cat:'all online reactjs mobile',
    gallery:[1,2,3,4,5],
    png: [4,5],
    link: 'https://crowdi.com.bo/',
    description: 'Web application of real estate crowd founding. The first version is going to be released on november 2020 in Bolivia.'
  },
  kingagame: {
    img:'kingagame/preview.jpg',
    title: 'Kinga Game',
    client: 'Ultimos Cartuchos',
    workplace: 'Freelance',
    type: 'Web Minigame',
    tools: ['Html5','JS','Cocos2d','CSS3','Dragonbones'],
    cat:'all design animations online games mobile',
    gallery:[1,2,3,4,5],
    png: [5],
    link: 'https://kingafichin.web.app/',
    description: 'This is a fan retro game for an argentinan radio show called "Ultimos Cartuchos" I listen to every day. A friend and I made this work without any reward, just for fun in a lockdown situation. I was in charge of the idea, the code, the music and the animations.'
  },
  rmcontrol: {
    img:'rmcontrol/preview.jpg',
    title: 'RM control panel',
    client: 'RM control',
    workplace: 'Freelance',
    type: 'Prototype design',
    tools: ['AdobeXD', 'Photoshop'],
    cat:'all design',
    gallery:[1,2,3,4,5,6],
    description: 'Design of the prototype for a dashboard to control claims and incidents made by new owners in the construction bussines.'
  },
  sanjorge: {
    img:'sanjorge/preview.jpg',
    title: 'San Jorge App',
    client: 'San Jorge School',
    workplace: 'Freelance',
    type: 'Mobile Application',
    tools: ['Ionic Framework 3'],
    cat:'all mobile',
    gallery:[1,2,3,4],
    png: [1,2,3,4],
    description: 'Mobile application for the educational community of a local school called "San Jorge" in which users are able to find discounts on local shops.'
  },
  happyhedgehog: {
    img:'happyhedgehog/preview.jpg',
    title: 'Happy Hedgehog',
    client: 'Livemedia',
    workplace: 'Livemedia',
    type: 'Mobile Game',
    tools: ['Cocos2d','Xcode','Android studio','Photoshop','Illustrator','Dragonbones', 'Photom', 'Playfab'],
    cat:'all online animations games mobile',
    gallery:[1,2,3],
    png:[1,2,3],
    link: 'https://play.google.com/store/apps/details?id=com.happyHegehog',
    description: 'A game developed in cocos2d js and published as a native app for IOS and Android. It consists of a runner game where the character has to avoid obstacles and cliffs in order to collect coins and bonus. The game has challenges for multiplayer mode and also contains his own shop connected with the stores.'
  },
  lares: {
    img:'lares/preview.jpg',
    title: 'Lares',
    client: 'Lares de Chacras',
    workplace: 'Pxsol',
    type: 'Hotel Web',
    tools: ['Html5','JS','JQuery','CSS3','AdobeXD','Photoshop','Illustrator'],
    cat:'all online design',
    gallery:[1,2,3,4,5],
    png: [4,5],
    link: 'https://www.laresdechacras.com/',
    description: 'Hotel web page design and development from the product department of Pxsol. I was in charge of the entire design proposition, development and maintenance of the web page.'
  },
  puertovalle: {
    img:'puertovalle/preview.jpg',
    title: 'Puerto Valle',
    client: 'Puerto Valle',
    workplace: 'Pxsol',
    type: 'Hotel Web',
    tools: ['Html5','JS','JQuery','CSS3','AdobeXD','Photoshop','Illustrator'],
    cat:'all online design mobile',
    gallery:[1,2,3,4,5],
    png: [1,2],
    link: 'https://www.hotelpuertovalle.com/',
    description: 'Hotel web page design and development from the product department of Pxsol. I was in charge of the entire design proposition, development and maintenance of the web page.'
  },
  sumare: {
    img:'sumare/preview.jpg',
    title: 'Sumare',
    client: 'Sumare Hotel',
    workplace: 'Pxsol',
    type: 'Hotel Web',
    tools: ['Html5','JS','JQuery','CSS3','AdobeXD','Photoshop','Illustrator'],
    cat:'all online design mobile',
    gallery:[1,2,3,4,5],
    png: [4,5],
    link: 'https://sulmarehotel.com/',
    description: 'Hotel web page design and development from the product department of Pxsol. I was in charge of the entire design proposition, development and maintenance of the web page.'
  },
  villamansa: {
    img:'villamansa/preview.jpg',
    title: 'Villa Mansa',
    client: 'Villa Mansa Hotel',
    workplace: 'Pxsol',
    type: 'Hotel Web',
    tools: ['Html5','JS','JQuery','CSS3','AdobeXD','Photoshop','Illustrator'],
    cat:'all online design mobile',
    gallery:[1,2,3,4,5],
    png: [1,2],
    link: 'https://www.villamansa.com/',
    description: 'Hotel web page design and development from the product department of Pxsol. I was in charge of the entire design proposition, development and maintenance of the web page.'
  },
  lechatelet: {
    img:'lechatelet/preview.jpg',
    title: 'Le Chatelet',
    client: 'Le Chatelet hotel',
    workplace: 'Pxsol',
    type: 'Hotel Web',
    tools: ['Html5','JS','JQuery','CSS3','AdobeXD','Photoshop','Illustrator'],
    cat:'all online design',
    gallery:[1,2,3],
    link: 'https://www.lechatelethotel.com/',
    description: 'Hotel web page design and development from the product department of Pxsol. I was in charge of the entire design proposition, development and maintenance of the web page.'
  },
  pxsol: {
    img:'pxsol/preview.jpg',
    title: 'Product landing and dashboard section',
    client: 'Pxsol',
    workplace: 'Pxsol',
    type: 'Landing web page and dashboard',
    tools: ['Design', 'Html5','JS','ReactJS','JQuery','CSS3','PHP','Google Charts'],
    cat:'all online reactjs mobile',
    gallery:[1,2,3],
    png:[3],
    link: 'https://pxsol.com',
    description: 'The main landing of 2018 with access to the description of products, clients and new projects for hotels. Dashboard section with graphic statistics of surveys and results for clients.'
  },
  selfietoon: {
    img:'selfietoon/preview.jpg',
    title: 'Selfie Toon',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','AngularJS','JS','GSAP','JQuery','CSS3','CreateJS','Social Sharing', 'Image Recognition'],
    cat:'all online animations angularjs mobile',
    gallery:[1,2,3,4,5],
    png:[1,2,3,4,5],
    link: 'https://watts.smartmonkeys.com.ar/cl/',
    description: 'Web application for Watts Chile. Contest where you have to find the stickers on the Watts products, scan them with image recognition and collect them for your album. Also you can take a selfie, customize with materials and share in social networks.'
  },
  mixtoons: {
    img:'mixtoons/preview.jpg',
    title: 'Mixtoons',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Animations'],
    cat:'all online animations',
    gallery:[1,2,3,4,5,6,7,8,9],
    png: [1,2,3,4,5],
    link: 'https://www.cartoonnetwork.com.ar/promo/mixtoons',
    description: 'Promo web app for CN Fan Art in latin america. Different challenges where you can mix the main characters of CN, upload your creation and participate in a voting contest.'
  },
  coloreando: {
    img:'coloreando/preview.jpg',
    title: 'Coloreando',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','CSS3'],
    cat:'all online mobile',
    gallery:[1,2,3],
    link:'https://www.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/bic-coloreando/',
    description: 'Web applications for kids to paint figures with the colores of BIC. You can use it on the mobile, choose different figures and print them.'
  },
  childrensday: {
    img:'childrensday/preview.jpg',
    title: 'Children&#39;s day',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Cocos2d'],
    cat:'all animations',
    gallery:[1,2,3,4,5],
    description: 'Landing web promo for latin america with 4 different mini games. In Mexico you play a fight with rock paper scissors mode, in Perú you have a truck adventure, in Brazil you have to dance, and in Argentina, you have to keep the football in the air.'
  },
  ayudaatumundo: {
    img:'ayudaatumundo/preview.jpg',
    title: 'Ayuda a tu mundo',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Animations'],
    cat:'all animations',
    gallery:[1,2,3],
    description: 'Landing web promo for "Help your world" where you can play 3 different minigames, download materials and interact with social networks.'
  },
  chismografo: {
    img:'chismografo/preview.jpg',
    title: 'Chismografo',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Animations'],
    cat:'all animations',
    gallery:[1,2],
    description: 'Web application that simulates a social network of Cartoon Network. You can interact with the characters, you can upload photos and videos, and make comments. You can add friends and view their profiles.'
  },
  teleheroes: {
    img:'teleheroes/preview.jpg',
    title: 'Teleheroes',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Animations'],
    cat:'all animations',
    gallery:[1,2],
    description: 'Landing web application where you can interact with a comic story and get different endings. You can call your favorite heroes to take place in the story using the phone.'
  },
  mesdelarisa: {
    img:'mesdelarisa/preview.jpg',
    title: 'Mes de la Risa',
    client: 'Cartoon Network',
    workplace: 'Livemedia',
    type: 'Web Application',
    tools: ['Html5','JS','GSAP','JQuery','CSS3','CreateJS','Animations'],
    cat:'all animations',
    gallery:[1,2,3,4],
    description: 'Landing web promo "laughter month" where you can modify pictures with funny materiales, distort them, and also, print, download or share your production.'
  }
};
